### ISSUE TITLE
Missing attributes due to updated script features

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [archin-software/bank2loyalty-api-php#1]
There are various model updates as of sept 9th 2021.

1, Introduced new reader screen "ShowEnterAmount"
2. new attribute ScriptAction in ScriptStep, 
3. new attributes keyStringScannedDataOverride en keyStringScannedCodeOverride in ShowOpticalScan model

See documentation https://developer.bank2loyalty.com

**Comment by tomdrissen** [comment]
New attributes are added, new 'ShowEnterAmount' will be added in PR #2.
