### ISSUE TITLE
Update needed because "language" attribute is added to ShowCard and ShowYesNoQuestion

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [archin-software/bank2loyalty-api-php#13]
Attribute "language" is added to ShowCard (for showing correct text in new label in case other than reader language is used) and ShowYesNoQuestion (for showing correct button text in case other than readerlanguage is used) See https://developer.bank2loyalty.com

**Comment by tomdrissen** [comment]
Added in version 0.0.11!
