### ISSUE TITLE
Support for Google SmartTap

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [archin-software/bank2loyalty-api-php#16]
The PHP libarary needs an update because of added support for Google SmartTap. 
Changes:
- IdenficationMeans has 2 new entries
- PostRequest has added field GoogleSmartTapInfo
- New class "GoogleSmartTapInfo"

For more info see https://developer.bank2loyalty.com

**Comment by tomdrissen** [comment]
Added in version 0.0.13
