### ISSUE TITLE
Update needed to reflect new features

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [archin-software/bank2loyalty-api-php#19]
As of Dec 5th. 

In ReaderInfo the field merchantDeviceLanguage has been added. The merchantdevice can be switched to another language (from version 1.4 and higher). At current en, nl, fr and de are supported, but more languages maybe added. 

An optional magnetic stripe reader can be attached to the reader. When the stripe is successfully read the stripe data is offered as scanneddata to the application with scannedCodes enum "MagneticStripe" with a value of 15.

**Comment by tomdrissen** [comment]
Added in version 1.0.1
