### ISSUE TITLE
Update needed to new graphics menu capability

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [archin-software/bank2loyalty-api-php#7]
There is a new screen added. This is a graphics menu, that can show options to choose from by presenting a script image. It has navigation buttons and a cancel button. Each menu choice has an image annotation label and a configurable button text/action. PHP code needs to be updated to support this new feature. See https://developer.bank2loyalty.com. This change requires changes in the scriptstep class and creation of 2 new php classes supporting the graphics menu.

Cheers, Martien

**Comment by tomdrissen** [comment]
Thanks Martien! We'll add the new classes next week.
